package:
  name: ghidra
  version: 11.1.2
  epoch: 0
  description: Ghidra is a software reverse engineering framework
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - gradle
      - libstdc++-6
      - libstdc++-6-dev
      - openjdk-21
      - python3
      - py3-pip
      - zip
  environment:
    SOURCE_DATE_EPOCH: 315532800
    JAVA_HOME: /usr/lib/jvm/java-21-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NationalSecurityAgency/ghidra
      tag: Ghidra_${{package.version}}_build
      expected-commit: 68cad06ddfae2b92c03054357c67c32f2d0553a8

  - runs: gradle -I gradle/support/fetchDependencies.gradle

  - runs: gradle buildGhidra

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      unzip -d ${{targets.destdir}}/usr/bin/ ./build/dist/*.zip
      mv ${{targets.destdir}}/usr/bin/ghidra_${{package.version}}_DEV ${{targets.destdir}}/usr/bin/ghidra

  - uses: strip

update:
  enabled: true
  github:
    identifier: NationalSecurityAgency/ghidra
    tag-filter: "11."

test:
  pipeline:
    - runs: |
        /usr/bin/ghidra/ghidraRun
